### ISSUE TITLE
iframe的属性

### ISSUE THREAD

**Issue by yanyunpiaomiao** [marmot-z/js-ratel-client#8]
iframe的scrolling给auto属性好一些，不然没有滚动条，右侧宽度可以再少点用百分比凑一百或者vw，加个F12监听事件，搞个拖动大小的插件就更完美了![图片](https://user-images.githubusercontent.com/50266991/150923086-a5e489cb-be94-4213-81df-0bb52ca3e6f3.png)

**Comment by marmot-z** [comment]
你好，感谢你提出的这个问题。这个项目暂时没有精力维护了，你可以到移步到 https://github.com/ratel-online 提此问题。
